# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Planit

on:
  push:
    branches: [ main ]
  schedule:
  - cron: '30 */1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upgrade to latest Planit version
      run: |
        git config --global user.name 'planit'
        git config --global user.email 'planit@tanjeffreyz.github.io'
        git config --global pull.rebase false
        git remote add planit 'https://github.com/tanjeffreyz/planit.git'
        git fetch planit
        git checkout planit/main src
        git checkout planit/main main.py
        git checkout planit/main index.html
        git checkout planit/main docs
        git checkout planit/main .gitignore
        git checkout planit/main requirements.txt
        git commit -m 'Upgraded to latest Planit version' || true
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Retrieve assignment information
      run: |
        python --version
        python main.py
      env:
        __ENV__
    
    - name: Commit new outputs
      run: |
        git add . || true
        git commit -m 'Updated assignments' || true
        git push origin main
        git push -f origin main:github-pages
